/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main.java.com.hotel.ui.maintenance;

/**
 *
 * @author shalaka
 */
public class MaintenanceMainPanel extends javax.swing.JPanel {

    /**
     * Creates new form MaintenanceMainPanel
     */
    public MaintenanceMainPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        maintenanceManagementTab = new javax.swing.JPanel();
        maintenanceManagementPanel1 = new main.java.com.hotel.ui.maintenance.MaintenanceManagementPanel();
        newmaintenanceRequestTab = new javax.swing.JPanel();
        newMaintenanceRequestPanel1 = new main.java.com.hotel.ui.maintenance.NewMaintenanceRequestPanel();

        setPreferredSize(new java.awt.Dimension(930, 660));

        javax.swing.GroupLayout maintenanceManagementTabLayout = new javax.swing.GroupLayout(maintenanceManagementTab);
        maintenanceManagementTab.setLayout(maintenanceManagementTabLayout);
        maintenanceManagementTabLayout.setHorizontalGroup(
            maintenanceManagementTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, maintenanceManagementTabLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(maintenanceManagementPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        maintenanceManagementTabLayout.setVerticalGroup(
            maintenanceManagementTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maintenanceManagementTabLayout.createSequentialGroup()
                .addComponent(maintenanceManagementPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jTabbedPane1.addTab("Maintenance Management", maintenanceManagementTab);

        javax.swing.GroupLayout newmaintenanceRequestTabLayout = new javax.swing.GroupLayout(newmaintenanceRequestTab);
        newmaintenanceRequestTab.setLayout(newmaintenanceRequestTabLayout);
        newmaintenanceRequestTabLayout.setHorizontalGroup(
            newmaintenanceRequestTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newmaintenanceRequestTabLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(newMaintenanceRequestPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        newmaintenanceRequestTabLayout.setVerticalGroup(
            newmaintenanceRequestTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newmaintenanceRequestTabLayout.createSequentialGroup()
                .addComponent(newMaintenanceRequestPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jTabbedPane1.addTab("New Maintenance Request", newmaintenanceRequestTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    private main.java.com.hotel.ui.maintenance.MaintenanceManagementPanel maintenanceManagementPanel1;
    private javax.swing.JPanel maintenanceManagementTab;
    private main.java.com.hotel.ui.maintenance.NewMaintenanceRequestPanel newMaintenanceRequestPanel1;
    private javax.swing.JPanel newmaintenanceRequestTab;
    // End of variables declaration//GEN-END:variables
}
