/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main.java.com.hotel.ui.booking;

import main.java.com.hotel.ui.dashboard.DashboardFrame;
import main.java.com.hotel.config.DatabaseConnection;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableCellRenderer;
import java.awt.Font;
import java.awt.Color;

/**
 *
 * @author shalaka
 */
public class BookingManagementPanel extends javax.swing.JPanel {

    private DashboardFrame parent;
    private boolean isDatabaseConnected = false;

    /**
     * Creates new form BookingManagementPanel
     */
    public BookingManagementPanel() {
        initComponents();
        setupBookingTable();
        loadBookingData();
    }

    public BookingManagementPanel(DashboardFrame parent) {
        this.parent = parent;
        initComponents();
        setupBookingTable();
        loadBookingData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        newBookingBtn = new javax.swing.JButton();
        filterPanel = new javax.swing.JPanel();
        searchLabel = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        resetLabelButton = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        statusCombobox = new javax.swing.JComboBox<>();
        dateLabel = new javax.swing.JLabel();
        fromLabel = new javax.swing.JLabel();
        dateFrom = new com.toedter.calendar.JDateChooser();
        toLabel = new javax.swing.JLabel();
        dateTo = new com.toedter.calendar.JDateChooser();
        bookingListPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookingListTable = new javax.swing.JTable();
        calenderViewPanel = new javax.swing.JPanel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setPreferredSize(new java.awt.Dimension(930, 660));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Booking Management");

        newBookingBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        newBookingBtn.setText("+ New Booking");

        searchLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchLabel.setText("Search :");

        searchTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        searchButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchButton.setText("search");

        resetLabelButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        resetLabelButton.setText("Reset");

        statusLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        statusLabel.setText("Status :");

        statusCombobox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        statusCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        statusCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusComboboxActionPerformed(evt);
            }
        });

        dateLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dateLabel.setText("Date :");

        fromLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fromLabel.setText("from");

        toLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        toLabel.setText("to");

        javax.swing.GroupLayout filterPanelLayout = new javax.swing.GroupLayout(filterPanel);
        filterPanel.setLayout(filterPanelLayout);
        filterPanelLayout.setHorizontalGroup(
            filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(filterPanelLayout.createSequentialGroup()
                        .addComponent(searchLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(filterPanelLayout.createSequentialGroup()
                        .addComponent(statusLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statusCombobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(filterPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(dateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fromLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(toLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateTo, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(157, Short.MAX_VALUE))
                    .addGroup(filterPanelLayout.createSequentialGroup()
                        .addComponent(searchButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resetLabelButton)
                        .addContainerGap())))
        );

        filterPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {searchLabel, statusLabel});

        filterPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {dateFrom, dateTo});

        filterPanelLayout.setVerticalGroup(
            filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(searchButton)
                        .addComponent(resetLabelButton))
                    .addComponent(searchLabel))
                .addGap(18, 18, 18)
                .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(statusLabel)
                        .addComponent(statusCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dateLabel)
                        .addComponent(fromLabel))
                    .addComponent(dateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toLabel)
                    .addComponent(dateTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        filterPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {dateFrom, dateLabel, dateTo, fromLabel, resetLabelButton, searchButton, searchLabel, searchTextField, statusCombobox, statusLabel, toLabel});

        jLabel8.setText("Booking List");

        bookingListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Booking", "Guest", "Room", "Check-in", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(bookingListTable);

        javax.swing.GroupLayout bookingListPanelLayout = new javax.swing.GroupLayout(bookingListPanel);
        bookingListPanel.setLayout(bookingListPanelLayout);
        bookingListPanelLayout.setHorizontalGroup(
            bookingListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingListPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bookingListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bookingListPanelLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        bookingListPanelLayout.setVerticalGroup(
            bookingListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingListPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addContainerGap())
        );

        calenderViewPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout calenderViewPanelLayout = new javax.swing.GroupLayout(calenderViewPanel);
        calenderViewPanel.setLayout(calenderViewPanelLayout);
        calenderViewPanelLayout.setHorizontalGroup(
            calenderViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        calenderViewPanelLayout.setVerticalGroup(
            calenderViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(newBookingBtn))
                    .addComponent(bookingListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(calenderViewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newBookingBtn)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(filterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bookingListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(calenderViewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, newBookingBtn});

    }// </editor-fold>//GEN-END:initComponents

    private void statusComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusComboboxActionPerformed

    /**
     * Setup the booking table with proper columns and styling
     */
    private void setupBookingTable() {
        // Table model with proper columns
        String[] columnNames = {"Booking #", "Guest", "Room", "Check-in", "Status"};
        DefaultTableModel model = new DefaultTableModel(columnNames, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Make table non-editable
            }
        };

        bookingListTable.setModel(model);

        // Table appearance
        bookingListTable.setRowHeight(25);
        bookingListTable.setFont(new Font("Arial", Font.PLAIN, 12));
        bookingListTable.getTableHeader().setFont(new Font("Arial", Font.BOLD, 12));
        bookingListTable.getTableHeader().setBackground(new Color(240, 240, 240));
        bookingListTable.setSelectionBackground(new Color(232, 242, 254));
        bookingListTable.setGridColor(new Color(240, 240, 240));
        bookingListTable.setShowVerticalLines(true);

        // Column widths
        if (bookingListTable.getColumnModel().getColumnCount() >= 5) {
            bookingListTable.getColumnModel().getColumn(0).setPreferredWidth(80);  // Booking #
            bookingListTable.getColumnModel().getColumn(1).setPreferredWidth(150); // Guest
            bookingListTable.getColumnModel().getColumn(2).setPreferredWidth(60);  // Room
            bookingListTable.getColumnModel().getColumn(3).setPreferredWidth(100); // Check-in
            bookingListTable.getColumnModel().getColumn(4).setPreferredWidth(80);  // Status
        }

        // Center alignment for certain columns
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(javax.swing.JLabel.CENTER);
        bookingListTable.getColumnModel().getColumn(0).setCellRenderer(centerRenderer); // Booking #
        bookingListTable.getColumnModel().getColumn(2).setCellRenderer(centerRenderer); // Room
        bookingListTable.getColumnModel().getColumn(3).setCellRenderer(centerRenderer); // Check-in
        bookingListTable.getColumnModel().getColumn(4).setCellRenderer(centerRenderer); // Status
    }

    /**
     * Load booking data from database or show sample data
     */
    private void loadBookingData() {
        try {
            // Test database connection
            if (!testDatabaseConnection()) {
                loadSampleBookingData();
                return;
            }

            // Get table model
            DefaultTableModel model = (DefaultTableModel) bookingListTable.getModel();

            // Clear existing data
            model.setRowCount(0);

            // Query for all bookings
            String query = "SELECT b.booking_number, "
                    + "CONCAT(g.first_name, ' ', g.last_name) AS guest_name, "
                    + "r.room_number, "
                    + "b.check_in_date, "
                    + "b.status "
                    + "FROM booking b "
                    + "JOIN guest g ON b.guest_id = g.guest_id "
                    + "JOIN booking_room br ON b.booking_id = br.booking_id "
                    + "JOIN room r ON br.room_id = r.room_id "
                    + "ORDER BY b.created_at DESC";

            ResultSet rs = DatabaseConnection.executeSearch(query);

            SimpleDateFormat dateFormat = new SimpleDateFormat("MMM dd, yyyy");

            while (rs.next()) {
                String bookingNumber = rs.getString("booking_number");
                String guestName = rs.getString("guest_name");
                String roomNumber = rs.getString("room_number");
                Date checkInDate = rs.getDate("check_in_date");
                String status = rs.getString("status");

                // Format check-in date
                String checkIn = checkInDate != null ? dateFormat.format(checkInDate) : "N/A";

                // Add row to table
                Object[] row = {bookingNumber, guestName, roomNumber, checkIn, status};
                model.addRow(row);
            }

            rs.close();

            // If no data found, show message
            if (model.getRowCount() == 0) {
                Object[] noDataRow = {"No bookings found", "", "", "", ""};
                model.addRow(noDataRow);
            }

        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("Error loading booking data: " + e.getMessage());
            loadSampleBookingData();
        }
    }

    /**
     * Test database connection
     */
    private boolean testDatabaseConnection() {
        try {
            String testQuery = "SELECT 1";
            ResultSet rs = DatabaseConnection.executeSearch(testQuery);
            boolean connected = rs.next();
            rs.close();
            return connected;
        } catch (Exception e) {
            System.out.println("Database connection failed: " + e.getMessage());
            return false;
        }
    }

    /**
     * Load sample booking data when database is not available
     */
    private void loadSampleBookingData() {
        DefaultTableModel model = (DefaultTableModel) bookingListTable.getModel();
        model.setRowCount(0);

        // Sample data
        Object[][] sampleData = {
            {"B202401", "John Smith", "101", "Dec 15, 2023", "Confirmed"},
            {"B202402", "Mary Johnson", "203", "Dec 14, 2023", "Checked-in"},
            {"B202403", "Robert Brown", "305", "Dec 13, 2023", "Checked-out"},
            {"B202404", "Lisa Wilson", "102", "Dec 12, 2023", "Confirmed"},
            {"B202405", "David Miller", "401", "Dec 11, 2023", "Cancelled"},
            {"B202406", "Sarah Davis", "204", "Dec 10, 2023", "Checked-in"},
            {"B202407", "Michael Garcia", "301", "Dec 09, 2023", "Checked-out"}
        };

        for (Object[] row : sampleData) {
            model.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bookingListPanel;
    private javax.swing.JTable bookingListTable;
    private javax.swing.JPanel calenderViewPanel;
    private com.toedter.calendar.JDateChooser dateFrom;
    private javax.swing.JLabel dateLabel;
    private com.toedter.calendar.JDateChooser dateTo;
    private javax.swing.JPanel filterPanel;
    private javax.swing.JLabel fromLabel;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton newBookingBtn;
    private javax.swing.JLabel resetLabelButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JComboBox<String> statusCombobox;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JLabel toLabel;
    // End of variables declaration//GEN-END:variables
}
